### ISSUE TITLE
Your funeral

### ISSUE THREAD

**Issue by vnuchaev** [LavirtheWhiolet/read2ch#1]
Я читал двач с комфортом, но в процессе чтения обнаружил у себя анальную боль. В честь этого я попытался связаться с автором данного приложения, но он не ответил на мои запросы. Если пользователь не отвечает, то наверное он мертв. Мы собрались провести групповые похороны. Сегодня, в 21:00 по московскому времени, будут похороны Л. Т. Белолетова.

Прийти на свои похороны всегда весело. Приглашаем в мамбл-конференцию радио Анонимус.

**Comment by LavirtheWhiolet** [comment]
П0EXABШNM
